spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: alibou
      password: alibou
      host: localhost
      port: 27017
      database: customer_db
      authentication-database: admin
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
